version: '3'

services:

  radio.app: 
    container_name: radio.app
    image: node
    ports:
      - "19080:5000"
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/outside/node_modules
    working_dir: /usr/src/app
    command: bash -c 'npm i && npm run start'
    links:
      - radio.mysql
    env_file:
      - ./env/.env.dev
  
  radio.mysql:
    container_name: radio.mysql
    image: mariadb:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file:
      - ./env/.env.dev
    ports: 
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin.reunion:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    links:
      - radio.mysql